name: ubuntu-software
version: git
summary: Application manager for GNOME
description: |
  Software allows you to find and install new applications and system
  extensions and remove existing installed applications.

  GNOME Software showcases featured and popular applications with useful
  descriptions and multiple screenshots per application.
  Applications can be found either through browsing the list of categories
  or by searching.
  It also allows you to update your system using an offline update.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic
base: base-18

slots:
  # for GtkApplication registration
  ubuntu-software:
    interface: dbus
    bus: session
    name: org.gnome.Software

apps:
  ubuntu-software:
    command: bin/desktop-launch $SNAP/usr/bin/gnome-software
    desktop: usr/share/applications/org.gnome.Software.desktop

parts:
  iso-codes:
    after: [desktop-gtk3]
    source: https://pkg-isocodes.alioth.debian.org/downloads/iso-codes-3.75.tar.xz
    plugin: autotools
    configflags: [--prefix=/snap/ubuntu-software/current/usr]
    organize:
      snap/ubuntu-software/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - gettext
      - python3
  gnome-desktop:
    after: [iso-codes]
    source: https://git.gnome.org/browse/gnome-desktop
    source-type: git
    source-tag: 3.26.2
    plugin: autotools
    prepare:
      sed -i.bak -e 's|.*ISO_CODES_PREFIX=.*|ISO_CODES_PREFIX=/snap/ubuntu-software/current/usr|g' configure.ac
    configflags: 
      - --prefix=/usr
      - --disable-date-in-gnome-version
      - --with-gnome-distributor=Ubuntu
      - --disable-debug-tools
      - --disable-desktop-docs
      - --enable-introspection=no
    organize:
      snap/ubuntu-software/current/usr: usr
    build-attributes: ['no-system-libraries']
    build-packages:
      - libglib2.0-dev
      - gnome-common
      - intltool
      - gnome-pkg-tools
      - gtk-doc-tools
      - docbook-xml
      - libx11-dev
      - xkb-data
      - libgdk-pixbuf2.0-dev
      - libgl1-mesa-dev
      - libgtk-3-dev
      - libxml2-dev
      - libglib2.0-doc
      - libgtk-3-doc
      - libseccomp-dev
      - libudev-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - gsettings-desktop-schemas-dev
      - yelp-tools
  ubuntu-software:
    build-attributes: [no-system-libraries]
    after: [gnome-desktop]
    source: .
    source-type: git
    prepare:
      sed -i.bak -e 's|Icon=org.gnome.Software$|Icon=${SNAP}/meta/gui/ubuntusoftware.svg|g' src/org.gnome.Software.desktop.in
    plugin: meson
    meson-parameters:
      - --prefix=/snap/ubuntu-software/current/usr
      - -Denable-gnome-desktop=true
      - -Denable-odrs=true
      - -Denable-ostree=false
      - -Denable-packagekit=true
      - -Denable-rpm=false
      - -Denable-snap=true
      - -Denable-fwupd=true
      - -Denable-flatpak=false
      - -Denable-limba=false
      - -Denable-ubuntu-reviews=true
      - -Denable-tests=false
    organize:
      snap/ubuntu-software/current/usr: usr
    build-packages:
      - appstream
      - appstream-util
      - docbook-xsl
      - gsettings-desktop-schemas-dev
      - gtk-doc-tools
      - intltool
      - libappstream-glib-dev
      - libfwupd-dev
      - libglib2.0-dev
      - libgnome-desktop-3-dev
      - libgtk-3-dev
      - libgtkspell3-3-dev
      - libgudev-1.0-dev
      - libjson-glib-dev
      - liboauth-dev
      - libpackagekit-glib2-dev
      - libpolkit-gobject-1-dev
      - libsecret-1-dev
      - libsoup2.4-dev
      - libsnapd-glib-dev
      - libsqlite3-dev
      - libxml2-utils
      - meson
      - pkg-config
      - valgrind
      - xsltproc
    stage-packages:
      - libappstream-glib8
      - libsecret-1-0
      - appstream
      - packagekit
      - libgnome-desktop-3-12
      - libgtkspell3-3-0
      - libfwupd2
      - libgudev-1.0-0
      - liboauth0
      - libsnapd-glib1
      - hicolor-icon-theme
      - humanity-icon-theme
      - light-themes
      - ubuntu-mono
      - ubuntu-settings

  # Extra libraries snapcraft complained about
  libraries:
    plugin: nil
    stage-packages:
      - libblkid1
      - libcomerr2
      - libgcrypt20
      - libgpg-error0
      - liblzma5
      - libmount1
      - libpcre3
      - libsystemd0
      - libtinfo5
      - libudev1
      - libuuid1
      - zlib1g
      - libgtk2.0-0
      - libstdc++6
  magic:
    after: [ubuntu-software]
    plugin: nil
    stage-packages:
      - libglib2.0-0
      - libglib2.0-bin
      - shared-mime-info
    install: |
      set -eux
      glib-compile-schemas $SNAPCRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      update-mime-database $SNAPCRAFT_PART_INSTALL/usr/share/mime
